# BA Toolkit — Project Initialiser (PowerShell)
# Usage: .\init.ps1
# Creates the output folder structure and a starter AGENTS.md for a new project.

param(
    [string]$Slug = "",
    [string]$Name = "",
    [string]$Domain = ""
)

Write-Host ""
Write-Host "  BA Toolkit — New Project Setup" -ForegroundColor Cyan
Write-Host "  ================================" -ForegroundColor Cyan
Write-Host ""

# --- Collect project info ---

if (-not $Slug) {
    $Slug = Read-Host "  Project slug (lowercase, hyphens only, e.g. dragon-fortune)"
}
$Slug = $Slug.ToLower() -replace '[^a-z0-9-]', '-' -replace '-+', '-' -replace '^-|-$', ''

if (-not $Name) {
    $Name = Read-Host "  Project name (human-readable, e.g. Dragon Fortune)"
}

if (-not $Domain) {
    Write-Host ""
    Write-Host "  Available domains:" -ForegroundColor Yellow
    Write-Host "    igaming      iGaming — slots, betting, casino, Telegram Mini Apps"
    Write-Host "    fintech      Fintech — neobanks, payments, crypto, P2P lending"
    Write-Host "    saas         SaaS — B2B platforms, CRM, analytics, EdTech"
    Write-Host "    ecommerce    E-commerce — stores, marketplaces, D2C brands"
    Write-Host "    healthcare   Healthcare — telemedicine, EHR, patient portals"
    Write-Host "    logistics    Logistics — delivery, courier, WMS, fleet"
    Write-Host "    on-demand    On-demand — ride-hailing, home services, marketplace"
    Write-Host "    social-media Social/Media — social networks, creator platforms"
    Write-Host "    real-estate  Real Estate — property portals, CRM, rental management"
    Write-Host "    custom       Custom — any other domain"
    Write-Host ""
    $Domain = Read-Host "  Domain"
}
$Domain = $Domain.ToLower().Trim()

# --- Determine output directory ---

$OutputDir = "output\$Slug"

# --- Create folder structure ---

Write-Host ""
Write-Host "  Creating project structure..." -ForegroundColor Green

$dirs = @(
    $OutputDir
)

foreach ($dir in $dirs) {
    if (-not (Test-Path $dir)) {
        New-Item -ItemType Directory -Path $dir | Out-Null
        Write-Host "    created  $dir" -ForegroundColor DarkGreen
    } else {
        Write-Host "    exists   $dir" -ForegroundColor DarkYellow
    }
}

# --- Create AGENTS.md ---

$today = Get-Date -Format "yyyy-MM-dd"
$agentsPath = "AGENTS.md"

if (Test-Path $agentsPath) {
    $overwrite = Read-Host "  AGENTS.md already exists. Overwrite? (y/N)"
    if ($overwrite -ne "y" -and $overwrite -ne "Y") {
        Write-Host "  Skipped AGENTS.md." -ForegroundColor DarkYellow
        $agentsPath = $null
    }
}

if ($agentsPath) {
    $agentsContent = @"
# BA Toolkit — Project Context

> Auto-generated by init.ps1 on $today. Updated automatically by /brief and /srs.

## Active Project

**Project:** $Name
**Slug:** $Slug
**Domain:** $Domain
**Language:** English
**Output folder:** output/$Slug/

## Pipeline Status

| Stage | Skill | Status | File |
|-------|-------|--------|------|
| 0 | /principles | ⬜ Not started | — |
| 1 | /brief | ⬜ Not started | — |
| 2 | /srs | ⬜ Not started | — |
| 3 | /stories | ⬜ Not started | — |
| 4 | /usecases | ⬜ Not started | — |
| 5 | /ac | ⬜ Not started | — |
| 6 | /nfr | ⬜ Not started | — |
| 7 | /datadict | ⬜ Not started | — |
| 7a | /research | ⬜ Not started | — |
| 8 | /apicontract | ⬜ Not started | — |
| 9 | /wireframes | ⬜ Not started | — |
| 10 | /scenarios | ⬜ Not started | — |
| 11 | /handoff | ⬜ Not started | — |

## Key Constraints

- Domain: $Domain
- (Add constraints after /brief completes)

## Key Stakeholder Roles

- (Populated after /srs completes)

## Open Questions

- (None yet)
"@

    Set-Content -Path $agentsPath -Value $agentsContent -Encoding UTF8
    Write-Host "    created  AGENTS.md" -ForegroundColor DarkGreen
}

# --- Done ---

Write-Host ""
Write-Host "  Project '$Name' ($Slug) initialised." -ForegroundColor Cyan
Write-Host ""
Write-Host "  Next steps:" -ForegroundColor Yellow
Write-Host "    1. Open your AI assistant (Claude, Cursor, etc.)"
Write-Host "    2. Optional: run /principles to define project-wide conventions"
Write-Host "    3. Run /brief to start the pipeline"
Write-Host ""
Write-Host "  Artifacts will be saved to: output\$Slug\" -ForegroundColor DarkGray
Write-Host ""
