#!/usr/bin/env bash
# BA Toolkit — Project Initialiser (bash)
# Usage: bash init.sh
#
# Creates the output folder structure and a starter AGENTS.md for a new
# project. This is a zero-dependency fallback for environments without
# Node.js. The recommended one-command setup is `npx @kudusov.takhir/ba-toolkit init`,
# which also installs skills into the chosen AI agent's directory.

set -e

CYAN='\033[0;36m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
DARK_GRAY='\033[0;90m'
BOLD='\033[1m'
RESET='\033[0m'

DOMAINS=(
    "saas|SaaS|B2B platforms, CRM, analytics, EdTech, HRTech"
    "fintech|Fintech|Neobanks, payments, crypto, P2P lending"
    "ecommerce|E-commerce|Stores, marketplaces, D2C brands, digital goods"
    "healthcare|Healthcare|Telemedicine, EHR, patient portals, clinic management"
    "logistics|Logistics|Delivery, courier, WMS, fleet management"
    "on-demand|On-demand|Ride-hailing, home services, task marketplaces"
    "social-media|Social/Media|Social networks, creator platforms, community forums"
    "real-estate|Real Estate|Property portals, agency CRM, rental management"
    "igaming|iGaming|Slots, betting, casino, Telegram Mini Apps"
    "custom|Custom|Any other domain — general interview questions"
)

echo ""
echo -e "  ${CYAN}BA Toolkit — New Project Setup${RESET}"
echo -e "  ${CYAN}================================${RESET}"
echo ""

# --- 1. Project name ---

if [ -z "$NAME" ]; then
    read -rp "  Project name (e.g. My App): " NAME
fi
NAME=$(echo "$NAME" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
if [ -z "$NAME" ]; then
    echo -e "  \033[0;31merror:\033[0m Project name is required." >&2
    exit 1
fi

# --- 2. Slug (auto-derived from name, user can override) ---

sanitise_slug() {
    echo "$1" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]/-/g' | sed 's/-\+/-/g' | sed 's/^-\|-$//g'
}

if [ -z "$SLUG" ]; then
    DERIVED=$(sanitise_slug "$NAME")
    if [ -n "$DERIVED" ]; then
        read -rp "  Project slug [${DERIVED}]: " SLUG
        SLUG="${SLUG:-$DERIVED}"
    else
        read -rp "  Project slug (lowercase, hyphens only): " SLUG
    fi
fi
SLUG=$(sanitise_slug "$SLUG")
if [ -z "$SLUG" ]; then
    echo -e "  \033[0;31merror:\033[0m Invalid or empty slug." >&2
    exit 1
fi

# --- 3. Domain (numbered menu) ---

if [ -z "$DOMAIN" ]; then
    echo ""
    echo -e "  ${YELLOW}Pick a domain:${RESET}"
    i=1
    for entry in "${DOMAINS[@]}"; do
        IFS='|' read -r id name desc <<< "$entry"
        printf "    %2d) ${BOLD}%-13s${RESET} ${DARK_GRAY}— %s${RESET}\n" "$i" "$name" "$desc"
        i=$((i + 1))
    done
    echo ""
    read -rp "  Select [1-${#DOMAINS[@]}]: " DOMAIN_CHOICE

    # Resolve digit or id
    if [[ "$DOMAIN_CHOICE" =~ ^[0-9]+$ ]]; then
        if [ "$DOMAIN_CHOICE" -ge 1 ] && [ "$DOMAIN_CHOICE" -le "${#DOMAINS[@]}" ]; then
            IFS='|' read -r DOMAIN _ _ <<< "${DOMAINS[$((DOMAIN_CHOICE - 1))]}"
        fi
    else
        DOMAIN_CHOICE=$(echo "$DOMAIN_CHOICE" | tr '[:upper:]' '[:lower:]' | xargs)
        for entry in "${DOMAINS[@]}"; do
            IFS='|' read -r id _ _ <<< "$entry"
            if [ "$id" = "$DOMAIN_CHOICE" ]; then
                DOMAIN="$id"
                break
            fi
        done
    fi

    if [ -z "$DOMAIN" ]; then
        echo -e "  \033[0;31merror:\033[0m Invalid selection." >&2
        exit 1
    fi
fi

# --- 4. Create folder structure ---

OUTPUT_DIR="output/$SLUG"

echo ""
echo -e "  ${GREEN}Creating project structure...${RESET}"

if [ ! -d "$OUTPUT_DIR" ]; then
    mkdir -p "$OUTPUT_DIR"
    echo -e "    created  $OUTPUT_DIR"
else
    echo -e "    exists   $OUTPUT_DIR"
fi

# --- 5. Create AGENTS.md ---

TODAY=$(date +%Y-%m-%d)
AGENTS_PATH="AGENTS.md"

if [ -f "$AGENTS_PATH" ]; then
    read -rp "  AGENTS.md already exists. Overwrite? (y/N): " OVERWRITE
    if [ "$OVERWRITE" != "y" ] && [ "$OVERWRITE" != "Y" ]; then
        echo "    skipped  AGENTS.md"
        AGENTS_PATH=""
    fi
fi

if [ -n "$AGENTS_PATH" ]; then
    cat > "$AGENTS_PATH" <<EOF
# BA Toolkit — Project Context

> Auto-generated by init.sh on $TODAY. Updated automatically by /brief and /srs.

## Active Project

**Project:** $NAME
**Slug:** $SLUG
**Domain:** $DOMAIN
**Language:** English
**Output folder:** output/$SLUG/

## Pipeline Status

| Stage | Skill | Status | File |
|-------|-------|--------|------|
| 0 | /principles | ⬜ Not started | — |
| 1 | /brief | ⬜ Not started | — |
| 2 | /srs | ⬜ Not started | — |
| 3 | /stories | ⬜ Not started | — |
| 4 | /usecases | ⬜ Not started | — |
| 5 | /ac | ⬜ Not started | — |
| 6 | /nfr | ⬜ Not started | — |
| 7 | /datadict | ⬜ Not started | — |
| 7a | /research | ⬜ Not started | — |
| 8 | /apicontract | ⬜ Not started | — |
| 9 | /wireframes | ⬜ Not started | — |
| 10 | /scenarios | ⬜ Not started | — |
| 11 | /handoff | ⬜ Not started | — |

## Key Constraints

- Domain: $DOMAIN
- (Add constraints after /brief completes)

## Key Stakeholder Roles

- (Populated after /srs completes)

## Open Questions

- (None yet)
EOF
    echo -e "    created  AGENTS.md"
fi

# --- 6. Done ---

echo ""
echo -e "  ${CYAN}Project '$NAME' ($SLUG) initialised.${RESET}"
echo ""
echo -e "  ${YELLOW}Next steps:${RESET}"
echo "    1. Install skills into your AI agent. The npm CLI does this in one shot:"
echo -e "         ${DARK_GRAY}npx @kudusov.takhir/ba-toolkit install --for claude-code${RESET}"
echo "       Or copy \`skills/\` manually — see the Manual install section in README.md."
echo "    2. Open your AI assistant (Claude, Cursor, etc.)"
echo "    3. Optional: run /principles to define project-wide conventions"
echo "    4. Run /brief to start the BA pipeline"
echo ""
echo -e "  ${DARK_GRAY}Artifacts will be saved to: output/$SLUG/${RESET}"
echo ""
