#!/usr/bin/env bash
# BA Toolkit — Project Initialiser (bash)
# Usage: bash init.sh
# Creates the output folder structure and a starter AGENTS.md for a new project.

set -e

CYAN='\033[0;36m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
DARK_GRAY='\033[0;90m'
RESET='\033[0m'

echo ""
echo -e "  ${CYAN}BA Toolkit — New Project Setup${RESET}"
echo -e "  ${CYAN}================================${RESET}"
echo ""

# --- Collect project info ---

if [ -z "$SLUG" ]; then
    read -rp "  Project slug (lowercase, hyphens only, e.g. dragon-fortune): " SLUG
fi
# Sanitise slug
SLUG=$(echo "$SLUG" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]/-/g' | sed 's/-\+/-/g' | sed 's/^-\|-$//g')

if [ -z "$NAME" ]; then
    read -rp "  Project name (human-readable, e.g. Dragon Fortune): " NAME
fi

if [ -z "$DOMAIN" ]; then
    echo ""
    echo -e "  ${YELLOW}Available domains:${RESET}"
    echo "    igaming      iGaming — slots, betting, casino, Telegram Mini Apps"
    echo "    fintech      Fintech — neobanks, payments, crypto, P2P lending"
    echo "    saas         SaaS — B2B platforms, CRM, analytics, EdTech"
    echo "    ecommerce    E-commerce — stores, marketplaces, D2C brands"
    echo "    healthcare   Healthcare — telemedicine, EHR, patient portals"
    echo "    logistics    Logistics — delivery, courier, WMS, fleet"
    echo "    on-demand    On-demand — ride-hailing, home services, marketplace"
    echo "    social-media Social/Media — social networks, creator platforms"
    echo "    real-estate  Real Estate — property portals, CRM, rental management"
    echo "    custom       Custom — any other domain"
    echo ""
    read -rp "  Domain: " DOMAIN
fi
DOMAIN=$(echo "$DOMAIN" | tr '[:upper:]' '[:lower:]' | xargs)

# --- Determine output directory ---

OUTPUT_DIR="output/$SLUG"

# --- Create folder structure ---

echo ""
echo -e "  ${GREEN}Creating project structure...${RESET}"

if [ ! -d "$OUTPUT_DIR" ]; then
    mkdir -p "$OUTPUT_DIR"
    echo -e "    created  $OUTPUT_DIR"
else
    echo -e "    exists   $OUTPUT_DIR"
fi

# --- Create AGENTS.md ---

TODAY=$(date +%Y-%m-%d)
AGENTS_PATH="AGENTS.md"

if [ -f "$AGENTS_PATH" ]; then
    read -rp "  AGENTS.md already exists. Overwrite? (y/N): " OVERWRITE
    if [ "$OVERWRITE" != "y" ] && [ "$OVERWRITE" != "Y" ]; then
        echo "  Skipped AGENTS.md."
        AGENTS_PATH=""
    fi
fi

if [ -n "$AGENTS_PATH" ]; then
    cat > "$AGENTS_PATH" <<EOF
# BA Toolkit — Project Context

> Auto-generated by init.sh on $TODAY. Updated automatically by /brief and /srs.

## Active Project

**Project:** $NAME
**Slug:** $SLUG
**Domain:** $DOMAIN
**Language:** English
**Output folder:** output/$SLUG/

## Pipeline Status

| Stage | Skill | Status | File |
|-------|-------|--------|------|
| 0 | /principles | ⬜ Not started | — |
| 1 | /brief | ⬜ Not started | — |
| 2 | /srs | ⬜ Not started | — |
| 3 | /stories | ⬜ Not started | — |
| 4 | /usecases | ⬜ Not started | — |
| 5 | /ac | ⬜ Not started | — |
| 6 | /nfr | ⬜ Not started | — |
| 7 | /datadict | ⬜ Not started | — |
| 7a | /research | ⬜ Not started | — |
| 8 | /apicontract | ⬜ Not started | — |
| 9 | /wireframes | ⬜ Not started | — |
| 10 | /scenarios | ⬜ Not started | — |
| 11 | /handoff | ⬜ Not started | — |

## Key Constraints

- Domain: $DOMAIN
- (Add constraints after /brief completes)

## Key Stakeholder Roles

- (Populated after /srs completes)

## Open Questions

- (None yet)
EOF
    echo -e "    created  AGENTS.md"
fi

# --- Done ---

echo ""
echo -e "  ${CYAN}Project '$NAME' ($SLUG) initialised.${RESET}"
echo ""
echo -e "  ${YELLOW}Next steps:${RESET}"
echo "    1. Open your AI assistant (Claude, Cursor, etc.)"
echo "    2. Optional: run /principles to define project-wide conventions"
echo "    3. Run /brief to start the pipeline"
echo ""
echo -e "  ${DARK_GRAY}Artifacts will be saved to: output/$SLUG/${RESET}"
echo ""
